config/routes.rb
Bracket::Application.routes.draw do
  get :login, to: 'sessions#new'
  post :login, to: 'sessions#create'
  delete :logout, to: 'sessions#destroy'

  resources :users do
    post :taken, on: :collection
  end

  get "/about", to: "pages#about"
  get '/_styleguide', to: 'pages#styleguide'

  root to: 'pages#index'
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates_uniqueness_of :username
  validates_uniqueness_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


private

  def logged_in?
    session[:user_id].present?
  end

  helper_method :logged_in?

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

  def styleguide
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.where(username: params[:username]).first
    if @user.try(:authenticate, params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Welcome back'
    else
      flash[:alert] = "Username or password incorrect. Try again"
      render :new
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def taken
    valid = User.where(username: params[:username]).empty?
    respond_to do |format|
      format.json { render json: { valid: valid } }
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Welcome to Bracket!' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title Bracket
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render 'partials/navbar'

    .flash
      - if flash[:notice].present?
        %p.notice= flash[:notice]
      - if flash[:alert].present?
        %p.alert= flash[:alert]
      - if flash[:info].present?
        %p.info= flash[:info]

    .wrapper

      = yield

app/views/pages/about.html.haml
%h1 About Bracket

%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.

%p Aliquam vulputate facilisis eros eu tristique. Suspendisse sed nulla id mi venenatis malesuada. Cras et urna sed ante placerat vulputate. Vestibulum quis nibh sem. Nulla facilisi. Nunc est erat, pellentesque in sagittis a, dignissim vitae justo. Donec consequat eros in lorem dignissim suscipit. Ut eget augue lorem. Aliquam erat volutpat.

%p Pellentesque porta arcu eget tellus consequat a dignissim urna imperdiet. Sed a ipsum mi, non congue sapien. Mauris tellus neque, sodales nec sagittis eu, fermentum eget metus. Suspendisse eleifend interdum eleifend. Praesent nec orci pretium enim blandit porta et quis felis. Phasellus a metus metus. Ut quis sapien nisl, sit amet egestas diam. Pellentesque nisl lectus, sagittis vitae tincidunt vitae, hendrerit quis eros. Phasellus a dui lorem, vel luctus tellus. Mauris sed nisi eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel velit nec tortor porttitor aliquam. Sed sit amet pharetra quam.

%p Pellentesque varius molestie gravida. Proin sit amet dui quis enim eleifend ultrices in id quam. Nam pretium malesuada tincidunt. Nullam sollicitudin tempor neque vel convallis. Curabitur metus sapien, pulvinar ut pretium at, ornare eget odio. Donec ligula justo, vestibulum ac congue eu, sodales a mi. Mauris a elit mauris.
%p Pellentesque varius molestie gravida. Proin sit amet dui quis enim eleifend ultrices in id quam. Nam pretium malesuada tincidunt. Nullam sollicitudin tempor neque vel convallis. Curabitur metus sapien, pulvinar ut pretium at, ornare eget odio. Donec ligula justo, vestibulum ac congue eu, sodales a mi. Mauris a elit mauris.
%p Pellentesque varius molestie gravida. Proin sit amet dui quis enim eleifend ultrices in id quam. Nam pretium malesuada tincidunt. Nullam sollicitudin tempor neque vel convallis. Curabitur metus sapien, pulvinar ut pretium at, ornare eget odio. Donec ligula justo, vestibulum ac congue eu, sodales a mi. Mauris a elit mauris.
%p Pellentesque varius molestie gravida. Proin sit amet dui quis enim eleifend ultrices in id quam. Nam pretium malesuada tincidunt. Nullam sollicitudin tempor neque vel convallis. Curabitur metus sapien, pulvinar ut pretium at, ornare eget odio. Donec ligula justo, vestibulum ac congue eu, sodales a mi. Mauris a elit mauris.
%p Pellentesque varius molestie gravida. Proin sit amet dui quis enim eleifend ultrices in id quam. Nam pretium malesuada tincidunt. Nullam sollicitudin tempor neque vel convallis. Curabitur metus sapien, pulvinar ut pretium at, ornare eget odio. Donec ligula justo, vestibulum ac congue eu, sodales a mi. Mauris a elit mauris.
%p Pellentesque varius molestie gravida. Proin sit amet dui quis enim eleifend ultrices in id quam. Nam pretium malesuada tincidunt. Nullam sollicitudin tempor neque vel convallis. Curabitur metus sapien, pulvinar ut pretium at, ornare eget odio. Donec ligula justo, vestibulum ac congue eu, sodales a mi. Mauris a elit mauris.

%p Integer posuere enim in enim elementum aliquet. Phasellus a felis dui, ut euismod neque. Sed sed dictum tortor. Proin semper tempus mi et egestas. Vestibulum lectus mi, sagittis ut accumsan id, dignissim et purus. Fusce nulla odio, condimentum id dictum id, volutpat a ante. Etiam id turpis id tellus feugiat iaculis.

app/views/pages/index.html.haml
%h1 Welcome to Bracket

%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.

%p Aliquam vulputate facilisis eros eu tristique. Suspendisse sed nulla id mi venenatis malesuada. Cras et urna sed ante placerat vulputate. Vestibulum quis nibh sem. Nulla facilisi. Nunc est erat, pellentesque in sagittis a, dignissim vitae justo. Donec consequat eros in lorem dignissim suscipit. Ut eget augue lorem. Aliquam erat volutpat.

%p Pellentesque porta arcu eget tellus consequat a dignissim urna imperdiet. Sed a ipsum mi, non congue sapien. Mauris tellus neque, sodales nec sagittis eu, fermentum eget metus. Suspendisse eleifend interdum eleifend. Praesent nec orci pretium enim blandit porta et quis felis. Phasellus a metus metus. Ut quis sapien nisl, sit amet egestas diam. Pellentesque nisl lectus, sagittis vitae tincidunt vitae, hendrerit quis eros. Phasellus a dui lorem, vel luctus tellus. Mauris sed nisi eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vel velit nec tortor porttitor aliquam. Sed sit amet pharetra quam.

%p Pellentesque varius molestie gravida. Proin sit amet dui quis enim eleifend ultrices in id quam. Nam pretium malesuada tincidunt. Nullam sollicitudin tempor neque vel convallis. Curabitur metus sapien, pulvinar ut pretium at, ornare eget odio. Donec ligula justo, vestibulum ac congue eu, sodales a mi. Mauris a elit mauris.

%p Integer posuere enim in enim elementum aliquet. Phasellus a felis dui, ut euismod neque. Sed sed dictum tortor. Proin semper tempus mi et egestas. Vestibulum lectus mi, sagittis ut accumsan id, dignissim et purus. Fusce nulla odio, condimentum id dictum id, volutpat a ante. Etiam id turpis id tellus feugiat iaculis.

app/views/pages/styleguide.haml
%h1 This is a h1
%h2 This is a h2
%h3 This is a h3
%h4 This is a h4

%hr

%h2 This is a paragraph
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.

%h2 Links
%a#link1{href: "#link1"} This link has been clicked
%br
%a#link2{href: "#link2"} Click me non active
%br
%a#link3.disabled{href: "#link3"} Cannot click

%h2 This is a form
%form
  .field
    %label Giant input with warning
    %input{ type: 'text', class: 'warning giant', placeholder: 'Giant input with warning' }
    %span.warning Warning text
  .field
    %label Large input with alert
    %input{ type: 'text', class: 'alert large', placeholder: 'Large input with alert' }
    %span.alert Alert text
  .field
    %label Default input with error
    %input{ type: 'text', class: 'error input', placeholder: 'Default input with error' }
    %span.error Error text
  .field
    %label Small info
    %input{ type: 'text', class: 'info small', placeholder: 'Input with info' }
    %span.info Info text
  .field
    %label Tiny success
    %input{ type: 'text', class: 'success tiny', placeholder: 'Tiny success' }
    %span.success Success text
  .field
    %label This is a large text area with info
    %textarea{ placeholder: 'A lot of text goes here', class: 'large info' }

  .actions
    %input{ type: 'submit', class: 'btn', value: 'Default button' }
    %input{ type: 'submit', class: 'btn primary', value: 'Primary button' }
    %input{ type: 'submit', class: 'btn secondary', value: 'Secondary button' }
    %input{ type: 'submit', class: 'btn disabled', value: 'Disabled button' }
    %input{ type: 'submit', class: 'btn warning', value: 'Warning button' }
    %input{ type: 'submit', class: 'btn info', value: 'Info button' }
    %input{ type: 'submit', class: 'btn danger', value: 'Danger button' }
    %input{ type: 'submit', class: 'btn inverse', value: 'Inverse button' }
    %input{ type: 'submit', class: 'btn giant', value: 'Giant button' }
    %input{ type: 'submit', class: 'btn large', value: 'Large button' }
    %input{ type: 'submit', class: 'btn small', value: 'Small' }
    %input{ type: 'submit', class: 'btn tiny primary', value: 'Tiny' }

%h2 This is a ordered list
%ol
  %li Item 1
  %li Item 2
  %li Item 3
  %li Item 4

%h2 This is a unorderd list
%ul
  %li Item 1
  %li Item 2
  %li Item 3
  %li Item 4

app/views/pages/stylesheet.haml
%h1 This is a h1
%h2 This is a h2
%h3 This is a h3
%h4 This is a h4

%hr

%h2 This is a paragraph
%p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at justo ac augue dictum adipiscing at et odio. Aenean porta ligula volutpat diam lobortis ac pretium lacus egestas. In nisi quam, blandit eu rutrum a, rhoncus a dolor. Maecenas vestibulum, mi non tempus vehicula, magna metus tincidunt leo, a hendrerit ligula urna ut metus. Maecenas sit amet libero justo, eget ultricies ante. Nulla mi elit, venenatis ut porta sit amet, semper ut dui. Nullam convallis scelerisque dolor, sed pulvinar eros rhoncus a. Nunc pharetra commodo leo eget lacinia. Proin et erat et nulla mollis ultrices. Etiam tempor malesuada felis eget eleifend. In vel metus sit amet nisi interdum molestie.

%h2 Links
%a#link1{href: "#link1"} This link has been clicked
%br
%a#link2{href: "#link2"} Click me non active
%br
%a#link3.disabled{href: "#link3"} Cannot click

%h2 This is a form
%form
  .field
    %label Giant input with warning
    %input{ type: 'text', class: 'warning giant', placeholder: 'Giant input with warning' }
    %span.warning Warning text
  .field
    %label Large input with alert
    %input{ type: 'text', class: 'alert large', placeholder: 'Large input with alert' }
    %span.alert Alert text
  .field
    %label Default input with error
    %input{ type: 'text', class: 'error input', placeholder: 'Default input with error' }
    %span.error Error text
  .field
    %label Small info
    %input{ type: 'text', class: 'info small', placeholder: 'Input with info' }
    %span.info Info text
  .field
    %label Tiny success
    %input{ type: 'text', class: 'success tiny', placeholder: 'Tiny success' }
    %span.success Success text
  .field
    %label This is a large text area with info
    %textarea{ placeholder: 'A lot of text goes here', class: 'large info' }

  .actions
    %input{ type: 'submit', class: 'btn', value: 'Default button' }
    %input{ type: 'submit', class: 'btn primary', value: 'Primary button' }
    %input{ type: 'submit', class: 'btn secondary', value: 'Secondary button' }
    %input{ type: 'submit', class: 'btn disabled', value: 'Disabled button' }
    %input{ type: 'submit', class: 'btn warning', value: 'Warning button' }
    %input{ type: 'submit', class: 'btn info', value: 'Info button' }
    %input{ type: 'submit', class: 'btn danger', value: 'Danger button' }
    %input{ type: 'submit', class: 'btn inverse', value: 'Inverse button' }
    %input{ type: 'submit', class: 'btn giant', value: 'Giant button' }
    %input{ type: 'submit', class: 'btn large', value: 'Large button' }
    %input{ type: 'submit', class: 'btn small', value: 'Small' }
    %input{ type: 'submit', class: 'btn tiny primary', value: 'Tiny' }

%h2 This is a ordered list
%ol
  %li Item 1
  %li Item 2
  %li Item 3
  %li Item 4

%h2 This is a unorderd list
%ul
  %li Item 1
  %li Item 2
  %li Item 3
  %li Item 4

app/views/partials/_navbar.haml
.navbar_wrapper
  .navbar
    .brand
      = link_to "Bracket", root_path, id: "brand"
    .nav
      = link_to 'About', about_path
      |
      - if logged_in?
        = link_to 'Sign up', new_user_path
        |
        = link_to 'Sign in', login_path
      - else
        = link_to 'Sign out', logout_path, method: :delete

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
    %span.success Username available
    %span.warning Username is already taken
    %span.error Username is too short
    %span.error.invalid Username is invalid
  .field
    = f.label :email
    = f.email_field :email
    %span.success Valid email
    %span.warning Invalid email
  .field
    = f.label :password
    = f.password_field :password, id: "original"
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation, id: "match"
    %span.success Passwords match
    %span.error Passwords do not match

  .actions
    = f.submit 'Sign up', id: "matchFields", class: 'btn primary', data: { original: "#original", match: "#match" }

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Username
    %th Email
    %th Password
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td= user.email
      %td= user.password
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path